### ISSUE TITLE
Buffer.alloc is not a function

### ISSUE THREAD

**Issue by DawoudIO** [queicherius/i18next-extract-gettext#2]
Getting the following on an install
```
vagrant@scotchbox:/vagrant$ npm install i18next-extract-gettext
npm ERR! Buffer.alloc is not a function
```

**Comment by queicherius** [comment]
`Buffer.alloc` needs node v4.5.0 (or newer). Please let me know if that fixes the issue or if not, which node version you are running. Thanks!

**Comment by queicherius** [comment]
Closing this since there was no feedback in a reasonable timeframe, so I assume the issue fixed itself. 😄
